version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install git
      - run: |
          DIR=$(dirname "$0")
          VERSION=$(git describe --abbrev=0 --tags)
          REVISION=$(git log "$VERSION..HEAD" --oneline | wc -l)

          function update_ai {
            f="$1"
            lead='^\/\/ TRAVIS\-CI: START REMOVE$'
            tail='^\/\/ TRAVIS\-CI: END REMOVE$'
            C=$(sed -e "/$lead/,/$tail/{ /$lead/{p; r insert_file
                  }; /$tail/p; d }" $f/Properties/AssemblyInfo.cs)
            echo "$C" > $f/Properties/AssemblyInfo.cs
            echo "[assembly: AssemblyVersion(\"$VERSION_STR.$REVISION\")]" >> $f/Properties/AssemblyInfo.cs
            echo "[assembly: AssemblyFileVersion(\"$VERSION_STR.$REVISION\")]" >> $f/Properties/AssemblyInfo.cs
            
            for nuspec in $f/*.nuspec; do
              if [[ -f "$nuspec" ]]; then
                echo "Processing nuspec file: $nuspec"
                padded=$(printf "%04d" $REVISION)
                sed -i.bak "s/\\\$version\\\$/$VERSION_STR-cibuild$padded/g" $nuspec
              fi
            done
          }

          re="([0-9]+\.[0-9]+\.[0-9]+)"
          if [[ $VERSION =~ $re ]]; then
            VERSION_STR="${BASH_REMATCH[1]}"
            echo "Version of $1 is now: $VERSION_STR"
            update_ai $DIR/../$1
          fi
      - run:
          name: Build
          command: dotnet build
      - run:
          name: NUnit Tests
          command: dotnet test SystemInteract.Tests
      - run:
          name: NuGet upload
          command: |
            set -e

            DIR=$(realpath $(dirname "$0"))
            P=$DIR/../$1

            cd $P

            sudo nuget update -self
            sudo chmod 0777 /tmp/NuGetScratch -R

            if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
              nuget pack *.nuspec -Prop Configuration=Release -BasePath $P

              nuget push *.nupkg -ApiKey $NUGET_API -Source https://www.nuget.org/api/v2/package
            fi