version: 2
workflows:
  version: 2
  untagged-build:
    jobs:
      - build
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y git
      - run:
          name: Build
          command: dotnet build
      - run:
          name: NUnit Tests
          command: dotnet test SystemInteract.Tests
      - run:
          name: NuGet upload
          command: |
            bash nuget-upload.sh SystemInteract
            bash nuget-upload.sh SystemInteract.Local
            bash nuget-upload.sh SystemInteract.Remote