version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y git nuget
      - run: |
          bash autoversion.sh SystemInteract
          bash autoversion.sh SystemInteract.Local
          bash autoversion.sh SystemInteract.Remote
      - run:
          name: Build
          command: dotnet build
      - run:
          name: NUnit Tests
          command: dotnet test SystemInteract.Tests
      - run:
          name: NuGet upload
          command: |
            bash nuget-upload.sh SystemInteract
            bash nuget-upload.sh SystemInteract.Local
            bash nuget-upload.sh SystemInteract.Remote