version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
      
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build SystemInteract.Net.Sln
      - run:
          name: NUnit Tests
          command: dotnet test SystemInteract.Tests