version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y git
      - run: |
          bash autoversion.sh SystemInteract
          bash autoversion.sh SystemInteract.Local
          bash autoversion.sh SystemInteract.Remote
      - run:
          name: Build
          command: dotnet build
      - run:
          name: NUnit Tests
          command: dotnet test SystemInteract.Tests
      - run:
          name: NuGet upload
          command: |
            set -e

            DIR=~/repo
            P=$DIR/../$1

            cd $P

            sudo nuget update -self
            sudo chmod 0777 /tmp/NuGetScratch -R

            if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
              nuget pack *.nuspec -Prop Configuration=Release -BasePath $P

              nuget push *.nupkg -ApiKey $NUGET_API -Source https://www.nuget.org/api/v2/package
            fi